### ISSUE TITLE
READMEにRequirementの項目がない

### ISSUE THREAD

**Issue by Nonchalant** [recruit-lifestyle/AIRValidator#1]
RequirementやCocoapodsの導入方法などが足りていないのので、
https://github.com/Alamofire/Alamofire
などの有名ライブラリを参照して修正すべき

**Comment by uny** [comment]
Requirementsは記載しました。
CocoaPodsの導入方法はさすがにAlamofireのように「iOS最近触り始めました」という人が入れるようなライブラリではない想定なので、不要かと思い省いています。
