### ISSUE TITLE
Swift2

### ISSUE THREAD

**Issue by Nonchalant** [recruit-lifestyle/AIRValidator#2]
Swift2のブランチがあったほうがいいと思います

**Comment by uny** [comment]
Swift2しか見てないです

**Comment by uny** [comment]
@Nonchalant 
Protocol Extension使ってるのでSwift2.0にのみ対応ですね。
あと、おそらく現状のライブラリは大抵masterが2.0向けかと。
https://github.com/recruit-lifestyle/AIRValidator/issues/1
が対応されればOKでしょうか？
であればクローズしてしまいます。

**Comment by Nonchalant** [comment]
現在はSwiftのバージョンが混在してる時期なので、GitHubのページを開いてSwiftのバージョンがすぐ分かる文面が必要かと思います。
Requirementを見れば分かると思いますが、少し面倒な気がします

**Comment by uny** [comment]
Xcode7.0+なのでさすがに大丈夫かと...
